# Generated by Django 6.1.1 on 2026-09-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(related_name='programmers', to='appname.language'),
        ),
    ]
